spring:
  #多数据源数据库连接配置
  datasource:
    #第一数据源配置
    primary:
      jdbc-url: jdbc:mysql://192.168.0.102:3306/test1
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
    #第二数据源配置
    secondary:
      jdbc-url: jdbc:mysql://192.168.0.102:3306/test2
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
  #jpa相关配置
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

